### ISSUE TITLE
Can't compile due to error in pubspec.yaml

### ISSUE THREAD

**Issue by marcqtan** [foureyez/ebreader#2] opened 2020-07-04 02:17 UTC
Hello, I'm trying this ereader but I can't seem to compile due to compile error in pubspec.yaml.. It cant find the ../epub-parser.

  epub_parser:
    path: ../epub-parser

Thanks

**Comment by foureyez** [comment] 2020-07-15 08:40
Hi,
This is a duplicate of : https://github.com/foureyez/ebreader/issues/1
Basically, i've commented the code in pubspec.yaml which picks the epub_parser library from github.
You can just go ahead and uncomment that and comment the above mentioned lines.

// Uncomment this
#  epub_parser:
#    git: https://github.com/foureyez/epub-parser.git

// Remove or comment this
  epub_parser:
    path: ../epub-parser

**Closed by foureyez** 2020-07-15 08:40 UTC
